### ISSUE TITLE
<yaml[].list_keys[]> not in correct order

### ISSUE THREAD

**Issue by monnierant** [DenizenScript/Denizen-For-Bukkit#1036]
Hi

I have an issue when i try to access to the yaml list_keys tag. It give me the correcte list of all keys but they are not ordered. Not by alphabetical name nor by the order in the yaml file.

...
`/ex narrate <yaml[confroutesoie].list_keys[routes.routesoie]>`
...
Result of my command
`li@Dest00|Dest60|Dest20|Dest40|Dest50|Dest10|Dest30`

Here it's my yaml file.
```
routes:
  routesoie:
    Dest00:
      name: 'Nefald'
      price: 10
      location: -420960,69,-54714,306,3,Harlan2
      captlocation: -420960,68,-54720,239,-5,Harlan2
      announce: 'Ha ca fait du bien de rentrer à la maison.'
    Dest10:
      name: 'Cité des mages'
      price: 12
      location: -415991,69,-50625,184,23,Harlan2
      captlocation: -415990,68,-50620,285,6,Harlan2
      announce: "Je ne descendrai pas de mon bateau. J'ai pas confiance en la magie."
    Dest20:
      name: 'Velmegun'
      price: 8
      location: -416766,69,-48573,87,16,Harlan2
      captlocation: -416760,68,-48573,223,16,Harlan2
      announce: 'Velmegun. On va faire le plein de bonnes affaires.'
    Dest30:
      name: 'Cercle des sages'
      price: 10
      location: -421690,69,-57468,265,5,Harlan2
      captlocation: -421697,68,-57468,135,3,Harlan2
      announce: 'On ne voit jamais les sages sur le port. On ne fait que livrer.'
    Dest40:
      name: 'Trahlim'
      price: 7
      location: -425071,69,-54977,214,-4,Harlan2
      captlocation: -425071,68,-54970,304,0,Harlan2
      announce: 'Quel belle ville Trahlim, allez donc faire un tour sur les quais.'
    Dest50:
      name: 'Providia'
      price: 13
      location: -422377,69,-50251,196,24,Harlan2
      captlocation: -422376,68,-50244,287,7,Harlan2
      announce: "Nous sommes toujours bienvenue à Providia et heureusement. Tant de sable qu'on en ramene des tonnes dans nos sandales."
    Dest60:
      name: 'Aldeiha'
      price: 8
      location: -424273,69,-50563,189,16,Harlan2
      captlocation: -424273,68,-50556,294,-6,Harlan2
      announce: "Nous sommes l'un des rares bateaux de nefald à ravitailler cette ile. Les habitants nous le rendent bien."
```
