### ISSUE TITLE
Workbench Inventory scripts

### ISSUE THREAD

**Issue by luigivampa** [DenizenScript/Denizen-For-Bukkit#1066]
```
[16:32] <luigi_vampa> the slots are borked
[16:32] <luigi_vampa> if the workbench slots are 0-9 and the crafted item slot 10
[16:33] <luigi_vampa> denizen reads the file and places them in the workbench starting at position 1
[16:33] <luigi_vampa> they're all offset one to the right. slot 9 is displayed in the crafted item slot 10

[16:38] <luigi_vampa> Look at this one 
http://mcmonkey.org/paste/16673

[16:38] <luigi_vampa> You'd assume the redstone would be in a column on the left?
[16:39] <luigi_vampa> the column is in the middle and the lever is in the crafted item slot

[16:41] <luigi_vampa> Here's another example Talamar 
http://mcmonkey.org/paste/16674
```
Sorry for the chat log. was typing this in the IRC!

**Comment by Morphan1** [comment]
You should be accounting for the result slot as the first slot. So like...
```
WorkbenchThing:
  type: inventory
  inventory: workbench
  slots:
  - "[]"
  - "[brick] [brick] [brick]"
  - "[] [brick] []"
  - "[] [] []"
```
Will correctly show things in a little T
