### ISSUE TITLE
Triggering an event each second

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1117]
I want to make a countdown for a minigame lobby, but with the `on time changes` event it only triggers each fiftieth second. But I want it to trigger in intervals of **one second**. How can I do that?

**Comment by mcmonkey4eva** [comment]
```YAML
myOncePerSecondScript:
  type: world
  events:
    on server start:
    - while true {
      - wait 1s
      - run looper
      }
looper:
  type: task
  script:
  - announce "LOOP!"
```
