### ISSUE TITLE
Block exploded event

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1134]
I wanna create a bomb gadget for my hub server which destroys blocks (drops primed_tnt) and then it should replace the blocks with a nice pop sound back after a few seconds. What event do I have to use for the exploded blocks?

**Comment by Talamar1** [comment]
on entity explodes
primed_tnt is an entity, not a block.

**Comment by brainscript** [comment]
@Talamar1 :smile_cat: I knew that this is an entity (otherwise I would be a bit stupid), but I thougt the event I searched for would trigger when a block gets broken by an explosion, something like `on block burns`. But with this event I can use the `<context.blocks>` to get the destroyed blocks. Thanks! :cake:

**Comment by brainscript** [comment]
My script currently looks like that:
```
bomb:
  type: world
  events:    
    on entity explodes:
    - define blocks <context.blocks>
    - wait <util.random.decimal[1].to[3]>
    - foreach %blocks% {
        - modifyblock <%value%> <%value%.material>
        - wait <util.random.decimal[0.1].to[0.5]>
        }
```
But in the `%blocks%` list only the location are saved and the materials are read out at runtime. How can I save the materials? I first thougt about cycling throug the `%blocks%` list at the start of the event and writing the blocks in a second list. But that would be a bit too complicated I think. Is there any easier solution?
