### ISSUE TITLE
in@inventory.title Only Works on CHEST Types

### ISSUE THREAD

**Issue by Mickket** [DenizenScript/Denizen-For-Bukkit#1224]
I reported this a while back on the irc and it was fixed but it seems that the more recent builds of Denizen have reverted the fix(?). All the containers in Minecraft support custom titles. Except for the anvil.
```
Hopper_Inv: 
  type: inventory 
  inventory: HOPPER
  title: "Hello <&4>World"
  slots: []
```
(Essentials command)
/i brewingstand 1 name:This&1Is&5A&4Title
/i hopper 1 name:This&1Is&5A&4Title
