### ISSUE TITLE
"HOLDING" in combination with discs and/or requirement mode "Any" not working

### ISSUE THREAD

**Issue by Jakky89** [DenizenScript/Denizen-For-Bukkit#123]
This is my script:

``` yaml
'DiscJockey':
  Type: Assignment
  Interact Scripts:
  - 10 DiscJockeyGreeting
  - 100 ^DiscJockeyChangeDisc
  Actions:
    ON ASSIGNMENT:
    - TRIGGER NAME:PROXIMITY TOGGLE:TRUE
    - TRIGGER NAME:CHAT TOGGLE:TRUE
    - TRIGGER NAME:CLICK TOGGLE:TRUE
'DiscJockeyGreeting':
  Type: Interact
  Requirements:
    Mode: None
  Steps:
    1:
      Proximity Trigger:
        Script:
        - LOOK CLOSE DURATION:5
        - CHAT 'Hallo, <PLAYER.NAME.DISPLAY>! Ich bin ein DJ und kann Schallplatten mit dir tauschen.'
        - NARRATE 'Rechtsklicke den NSC mit der Schallplatte, die du umtauschen möchtest.'
      Click Trigger:
        Script:
        - LOOK CLOSE DURATION:2
        - LOOK AWAY
        - CHAT 'Das war wohl nichts ...'
'DiscJockeyChangeDisc':
  Type: Interact
  Requirements:
    Mode: Any
    List:
    - HOLDING ITEM:2257
    - HOLDING ITEM:2258
    - HOLDING ITEM:2259
    - HOLDING ITEM:2260
    - HOLDING ITEM:2261
    - HOLDING ITEM:2262
    - HOLDING ITEM:2263
    - HOLDING ITEM:2264
    - HOLDING ITEM:2265
    - HOLDING ITEM:2266
    - HOLDING ITEM:2267
  Steps:
    1:
      Click Trigger:
        Script:
        - LOOK CLOSE DURATION:5
        - TAKE ITEMINHAND QTY:1
        - CHAT 'Danke!'
        - CHAT 'Welche Schallplatte möchtest du dafür haben?'
        - HINT
      Chat Trigger:
        1:
          Trigger: Die mit dem Titel /13/
          Script:
          - GIVE ITEM:2256
        2:
          TRIGGER: Die mit dem Titel /cat/
          Script:
          - GIVE ITEM:2257
        3:
          TRIGGER: Die mit dem Titel /blocks/
          Script:
          - GIVE ITEM:2258
        4:
          TRIGGER: Die mit dem Titel /chirp/
          Script:
          - GIVE ITEM:2259
        5:
          TRIGGER: Die mit dem Titel /far/
          Script:
          - GIVE ITEM:2260
        6:
          TRIGGER: Die mit dem Titel /mall/
          Script:
          - GIVE ITEM:2261
        7:
          TRIGGER: Die mit dem Titel /mellohi/
          Script:
          - GIVE ITEM:2262
        8:
          TRIGGER: Die mit dem Titel /stal/
          Script:
          - GIVE ITEM:2263
        9:
          TRIGGER: Die mit dem Titel /strad/
          Script:
          - GIVE ITEM:2264
        10:
          TRIGGER: Die mit dem Titel /ward/
          Script:
          - GIVE ITEM:2265
        11:
          TRIGGER: Die mit dem Titel /11/
          Script:
          - GIVE ITEM:2266
        12:
          TRIGGER: Die mit dem Titel /wait/
          Script:
          - GIVE ITEM:2267
```

The requirement mode "Any" in combination with "HOLDING" discs doesn't seem to work at all. I tried in different ways...
