### ISSUE TITLE
[Question] Text below name

### ISSUE THREAD

**Issue by brainscript** [DenizenScript/Denizen-For-Bukkit#1232]
I want to display the rank of every player below his name.
```
rk_config:
    type: yaml data
    ranks:
        Owner:
            name: Owner
            prefix: <&4>
        Admin:
            name: Admin
            prefix: <&6>
        Moderator:
            name: Moderator
            prefix: <&3>
        Builder:
            name: Builder
            prefix: <&2>
        Youtuber:
            name: YouTuber
            prefix: <&5>
        Premium:
            name: Premium
            prefix: <&b>
        Player:
            name: Spieler
            prefix: <&e>

rk_starter:
  type: world
  events:
    on server start:
    - run "s@rk_loop" instantly

rk_loop:
    type: task
    script:
    - foreach <server.list_online_players> {
        - define rank <s@rk_config.yaml_key[ranks.<%value%.groups.get[1]>.name]>
        - define prefix <parse:<s@rk_config.yaml_key[ranks.<%value%.groups.get[1]>.prefix]>>
        - scoreboard add viewers:<server.list_online_players.exclude[%value%]> id:<%value%.name> obj:%prefix%%rank% criteria:dummy displayslot:below_name
        }
    - wait 1s
    - run "s@rk_loop" instantly
```
I tested a few ways of doing this, that's why it looks a bit messed up.
It works so far with two players, but when a third player joins, it shows the rank of one of the two players below the names of both.

I see the rank of the last player in the `foreach` loop below both names.

Player | Real rank | Displayed rank 
------------- | ----------- | ----------------
brainscript | Owner | -
Player1 | Builder | Player
Player2 | Player | Player

How can I do this? Please help me. :smile_cat:
