### ISSUE TITLE
Give existing command permission

### ISSUE THREAD

**Issue by ArmyOps** [DenizenScript/Denizen-For-Bukkit#1257]
I downloaded shop plugin where /shop command doesnt have permission node. I wanted to give it permission so that players are not able to open shop everywhere and ppls with permission node could.
But how exactly i can do it, cuz i cant figure out how to make it run it.
At the moment it disabled the command for everyone and permission doesnt fix it also. I have really no glue what im doing there, so far i have used written scripts but cant find any to help out with that one.
```
shop:
    type: command
    name: shop
    permission: shop.shop
    script:
    - if <player.has_permission[shop.shop]> { - execute [as_player] } else { - chat "You don't have the perms!" }
```
~~For some reason had to put # after -if, cuz it cleared that part..~~
