### ISSUE TITLE
"on player right clicks entity" doesn't fire with entity script

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1263]
The event doesn't fire if an entity script is specified, rather than a normal entity.

```yaml
pEnt:
  type: entity
  entity_type: e@villager
  has_ai: false
  custom_name: Bob

pEnt_Handler:
  type: world
  events:
    on player right clicks pEnt:
    - determine passively cancelled
    - narrate "Oops!"
```

Current work around required:
```yaml
pEnt:
  type: entity
  entity_type: e@villager
  has_ai: false
  custom_name: Bob

pEnt_Handler:
  type: world
  events:
    on player right clicks villager:
    - if <context.entity.scriptname.is[!=].to[pEnt]||true> {
      - queue clear
    }
    - determine passively cancelled
    - narrate "Oops!"
```
