### ISSUE TITLE
Make Respawn Delay work again

### ISSUE THREAD

**Issue by GomaTerzuTheSecond** [DenizenScript/Denizen-For-Bukkit#1266]
We talked about this on IRC Chat some minutes ago but I want to add it here, too, so it is not forgotten.
The problem is, that you can't manage the npc respawn delay in an easy way through existing commands. 

There is the /npc respawn command where you can specify the respawn in ticks. But no matter what you set, the NPC always respawns way to fast.

There is also the /npc health --respawndelay command where you can specifiy the time in any possible way and it calculates it in ticks.

Both do not work properly.

When you add the health trait to NPCs it looks like this in the citizens saves.yml

```
      health:
        animatedeath: true
        respawnondeath: true
        respawndelayinseconds: 20s
```

The 20s come from the denizen config.yml

```
Traits:
  Health:
    Enabled: true
    Respawn:
      Enabled: true
      Delay: 20s
    Animated death:
      Enabled: true
```
