### ISSUE TITLE
Potatoes in inventories.

### ISSUE THREAD

**Issue by Explanationator** [DenizenScript/Denizen-For-Bukkit#1268]
If you try and put "i@potato" inside the "slots:" part of an inventory script, it opens, but no potato. Other items in the same menu work just fine and show up. I've tried with multiple inventory scripts.

Random example on one of my menus:
```
basicCookingMenuRecipeNew: 
    type: inventory
    inventory: CHEST
    title: "<Aqua>Basic Cooking Menu - Cook"
    size: 9
    slots:
    - "[i@potato] [] [] [] [] [] [] [] [recipeDone]"
```
