### ISSUE TITLE
Inventory script empty space

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Denizen-For-Bukkit#1285]
Inventory scripts aren't properly recognizing empty space `[]` in the slots section.
Current work around is to fill empty space with air `[i@air]` however in accorance to the inventory script container... it should automatically fill empty slots with air.
![ss 2016-01-22 at 07 09 42](https://cloud.githubusercontent.com/assets/598503/12527333/2b59d0c0-c1cd-11e5-95b8-d6cd0c6003e0.png)

**Comment by Morphan1** [comment]
This makes no sense. The leading spaces clearly indicate that `[]` is working. Are there errors in the console?

**Comment by Fortifier42** [comment]
It's actually an issue posting for someone else on the IRC, I've tested it and encountered the same issue, and it's quite common amongst IRC newbies. It appears to be ignoring the ending spaces, however registers the previous ones.

**Comment by Fortifier42** [comment]
Re-tested just then.

http://puu.sh/mHkiR.png - Image of inventory opened
Debug: http://mcmonkey.org/paste/29003
Script:
```YAML
Inv:
  type: inventory
  size: 27
  definitions:
    x: i@barrier
  slots:
  - "[] [] [x] [] [] [] [] [] []"
  - "[] [] [x] [] [] [] [] [] []"
  - "[] [] [x] [] [] [] [] [] []"
```
