### ISSUE TITLE
Chat and proximity triggers not working (?)

### ISSUE THREAD

**Issue by Jakky89** [DenizenScript/Denizen-For-Bukkit#129]
I don't know if it's a mistake in my denizen scripts but it seems like the chat and proximity triggers arn't working.

At first, here is one of my scripts:

``` yaml
'DiscJockey':
  Type: Assignment
  Interact Scripts:
  - 10 DiscJockeyGreeting
  - 20 DiscJockeyChangeDisc
'DiscJockeyGreeting':
  Type: Interact
  Requirements:
    Mode: None
  Steps:
    '1':
      Proximity Trigger:
        Script:
        - CHAT 'Hallo, <PLAYER.NAME.DISPLAY>! Ich bin ein DJ und kann Schallplatten mit dir tauschen.'
        - NARRATE 'Rechtsklicke den NSC mit der Schallplatte, die du umtauschen möchtest.'
      Click Trigger:
        Script:
        - CHAT 'Du hast keine Schallplatte in der Hand.'
'DiscJockeyChangeDisc':
  Type: Task
  Requirements:
    Mode: Any 1
    List:
    - HOLDING 2256
    - HOLDING 2257
    - HOLDING 2258
    - HOLDING 2259
    - HOLDING 2260
    - HOLDING 2261
    - HOLDING 2262
    - HOLDING 2263
    - HOLDING 2264
    - HOLDING 2265
    - HOLDING 2266
    - HOLDING 2267
  Steps:
    '1':
      Click Trigger:
        Script:
        - TAKE ITEMINHAND QTY:1
        - CHAT 'Danke!'
        - CHAT 'Welche Schallplatte möchtest du dafür haben?'
      Chat Trigger:
        '1':
          Trigger: Die mit dem Titel /13/
          Script:
          - GIVE ITEM:2256
        '2':
          TRIGGER: Die mit dem Titel /cat/
          Script:
          - GIVE ITEM:2257
        '3':
          TRIGGER: Die mit dem Titel /blocks/
          Script:
          - GIVE ITEM:2258
        '4':
          TRIGGER: Die mit dem Titel /chirp/
          Script:
          - GIVE ITEM:2259
        '5':
          TRIGGER: Die mit dem Titel /far/
          Script:
          - GIVE ITEM:2260
        '6':
          TRIGGER: Die mit dem Titel /mall/
          Script:
          - GIVE ITEM:2261
        '7':
          TRIGGER: Die mit dem Titel /mellohi/
          Script:
          - GIVE ITEM:2262
        '8':
          TRIGGER: Die mit dem Titel /stal/
          Script:
          - GIVE ITEM:2263
        '9':
          TRIGGER: Die mit dem Titel /strad/
          Script:
          - GIVE ITEM:2264
        '10':
          TRIGGER: Die mit dem Titel /ward/
          Script:
          - GIVE ITEM:2265
        '11':
          TRIGGER: Die mit dem Titel /11/
          Script:
          - GIVE ITEM:2266
        '12':
          TRIGGER: Die mit dem Titel /wait/
          Script:
          - GIVE ITEM:2267
```

At first the npc should say something if you go near it but it doesn't. Secondly it takes the disc when a player right clicks it with the disc in hand (that works) and after that it should react to players chat input and give out the wanted disc when they say one of the keywords (the disc name) but that doesn't work.

Can you please tell me if it's a mistake in my script (never got it working with whatever I tried) or if it's a bug? And if it is a bug, could you please fix it?
