### ISSUE TITLE
save argument for run command

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#1427]
can we pls has this
```
script:
  type: task
  script:
  - determine "blah"
script2:
  type: task
  script:
  - run script save:ID
  - narrate <entry[ID].return>
```

would narrate "blah"
pls? :c
