### ISSUE TITLE
I'm a Nooob (this is not that important)

### ISSUE THREAD

**Issue by TheSodaPopPanda** [DenizenScript/Denizen-For-Bukkit#1431]
ok so like the title say's I'm new to denizens so sorry if this is a basic mistake! but my Proximity Trigger is not working no errors in console its just not working, thanks. PS (take your time **important**)
```
Welcome:
    type: assignment
    interact scripts:
    - 1 help
    - 2 welcome

help:
    type: interact
    steps:
        1:

            chat trigger:
                1:
                    trigger: /Yes/
                    script:
                    - execute as_player "cc open Welcome.yml"

                2:
                    trigger: /No/,
                    script:
                    - chat "Okay, Well if you need help please come back."

                3:
                    trigger: /help/,
                    script:
                    - chat "Woops, Sorry do you need help?."
                    - chat "&2&lyes&7&l/&4&lNo"
                4:
                    trigger: /Hi/,
                    script:
                    - chat "Hello, can I help you?."
                    - chat "&2&lyes&7&l/&4&lNo"

                5:
                    trigger: /Hello/,
                    script:
                    - chat "oh,Hi do you need help?."
                    - chat "&2&lyes&7&l/&4&lNo"


welcome:
    type: interact
    steps:
        1:

           Proximity Trigger:
                entry:
                    Script:
                    - CHAT "Welcome, <player.name>!
                exit:
                    Script:
                    - CHAT "Goodbye, <player.name>!"
```

**Comment by mcmonkey4eva** [comment]
You missed a few bits and overcomplicated a bit.
Try it like this:
```
Welcome:
    type: assignment
    actions:
        on assignment:
        - trigger name:chat state:true
        - trigger name:proximity state:true
    interact scripts:
    - 1 help

help:
    type: interact
    steps:
        1:

            chat trigger:
                1:
                    trigger: /Yes/
                    script:
                    - execute as_player "cc open Welcome.yml"

                2:
                    trigger: /No/,
                    script:
                    - chat "Okay, Well if you need help please come back."

                3:
                    trigger: /help/,
                    script:
                    - chat "Woops, Sorry do you need help?."
                    - chat "&2&lyes&7&l/&4&lNo"
                4:
                    trigger: /Hi/,
                    script:
                    - chat "Hello, can I help you?."
                    - chat "&2&lyes&7&l/&4&lNo"

                5:
                    trigger: /Hello/,
                    script:
                    - chat "oh,Hi do you need help?."
                    - chat "&2&lyes&7&l/&4&lNo"
           proximity trigger:
                entry:
                    script:
                    - chat "Welcome, <player.name>!
                exit:
                    script:
                    - chat "Goodbye, <player.name>!"

```
