### ISSUE TITLE
Adjusting "item_on_cursor" doesn't work?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1492]
I'm using the script below to simulate equipping a helmet with a block item:
```YAML
0_pumpkinHelmetSkill:
  type: world
  debug: false
  events:
    on player clicks in inventory:
    - if <context.inventory.id_type> == PLAYER
    {
      - if <context.slot_type> == ARMOR && <context.slot> == 40 && <context.cursor_item.scriptname||null> == 0_pumpkinHelmet
      {
        - equip <player> head:0_pumpkinHelmet
        - adjust <player> "item_on_cursor:i@air"
      }
      
      - if <player.name> == GrandPartyMask
      {
        - narrate '<context.slot_type> <context.slot> <context.raw_slot> <player.item_on_cursor>'
      }
    }
```

When I try to click on the helmet slot, the Jack O'Lantern on my cursor is not replaced with air nor is the Jack O'Lantern equipped. It simply acts as if the script doesn't exist, the Jack O'Lantern does not do anything. This video (caught in Survival mode) might help a little bit: https://youtu.be/H9F8H7OmGIA. The console log is here: https://i.gyazo.com/31864c4197f4d8f5e9a512d3fb2b87b4.png (I excluded the part where it narrates the slot information back to me).
