### ISSUE TITLE
rotate command + lookclose NPC trait = neck snapping galore

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1507]
Currently using the latest Spigot 1.11 build along with the latest Denizen_Development and Citizens builds. When I use the ```rotate``` command with Denizen, the NPC rotates just fine. Combined with ```lookclose``` in a modified version of the ```"npcsmartlook"``` script, the NPC does not return to rotating normally. When a player exits the lookclose range, the NPC's head snaps to the direction that it was looking at before the player entered the lookclose range.

Video/GIF showing such can be found here: http://i.imgur.com/8zegwGn.gifv
Relevant script is here: http://pastebin.com/xp19UTAM

**Comment by GomaTerzu** [comment]
What citizens build do you use? There was a problem with heads snapping back that was fixxed a few days ago.

Your rotate command in line 55. is also missing a space to be in line with the other commands.

**Comment by MusicScore** [comment]
@GomaTerzu No, it's definitely correctly formatted. For some reason, pastebin edited the spacing. Here's the raw script:

```yaml
# +------------------- 
# | N P C 
# | S M A R T L O O K 
# | 
# | NPCs that look around realistically! 
# 
# @author mcmonkey 
# @date 2014 / 12 / 8 
# @build 1546 
# @version 1.0 
# 
# Installation: 
# Copy into your scripts folder and /denizen reload scripts 
# 
# Usage: 
# /npc select            # Select an NPC 
# /ex flag npc smartlook # Enable smartlook functionality

# Modified by: GrandPartyMask

npcsmartlook_world_handler: 
  type: world 
  debug: false
  
  events: 
    on server start: 
    - inject locally "events.on reload scripts" 
    on reload scripts:
    - foreach <queue.list>
    {
      - if <def[value].script> == s@npcsmartlook_task_run
      {
        - queue <def[value]> stop
      }
    } 
    - wait 10t 
    - run npcsmartlook_task_run delay:10t 

npcsmartlook_task_run: 
  type: task 
  debug: false
  
  script: 
  - async
  {
    - while true
    {
      - foreach <server.get_npcs_flagged[smartlook]>
      {
        - if !<def[value].has_flag[smartlookcooldown]> && <util.random.int[1].to[4]> == 1 && <def[value].is_spawned> && <def[value].location.find.players.within[5].size> == 0
        {
          - define turn_yaw <util.random.int[-10].to[10]> 
          - define turn_time <util.random.decimal[0.5].to[3.5]> 
          - define turn_tick_frequency <util.random.int[4].to[6]>
          - rotate <def[value]> 'yaw:%turn_yaw%' 'pitch:0' 'duration:%turn_time%s' 'frequency:%turn_tick_frequency%t'
          - define flag_expiration <util.random.int[<el@val[%turn_time%].round_up>].to[<el@val[%turn_time%].round_up.add[7]>]>
          - flag <def[value]> smartlookcooldown duration:%flag_expiration%s
        }
        else if <def[value].is_spawned> && <def[value].location.find.players.within[5].size> >= 1
        {
          - rotate cancel <def[value]>
        }
      }
      - wait 1s
    }
  }
```
