### ISSUE TITLE
Define command cannot read other definitions

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1548]
I'm using the latest Denizen_Developmental version, along with the latest Depenizen and Spigot files.

While I was trying to write an inventory script with procedural items, I discovered that the ```define``` command apparently couldn't read the definition defined by another ```define``` command. For example,
```yaml
inventory_test_script:
  type: inventory
  debug: false
  inventory: CHEST
  title: '<&8>Test'
  size: 9
  procedural items:
  - define 'item_list' 'li@'
  - define 'black_glass_pane' 'i@black_stained_glass_pane[display_name=&ss0]'
  - repeat 9:
    - define 'item_list' '<def[item_list].include[<def[black_glass_pane]>]>'
  - determine '<def[item_list]>'
```

When I ran a ```narrate``` command for the final result for ```<def[item_list]>```, I found that the definition resulted in ```<def[item_list].include[<def[black_glass_pane]>]>``` instead of ```li@i@black_stained_glass_pane[display_name=&ss0]|...```

This also happened with other scripts of mine. For example,
```yaml
task_test_script:
  type: task
  debug: false
  script:
  - define 'location_1' '<l@0,0,0,world>'
  - define 'location_2' '<l@10,10,10,world>'
  - define 'new_cuboid' '<cu@%location_1%|%location_2%>'
  - narrate '<def[new_cuboid]>'
```
The console would return an error saying that ```<def[new_cuboid]>``` is not a valid cuboid, since ```%location_1%``` and ```%location_2%``` were invalid locations, despite both having been specified beforehand.
I'm able to work around these by not using definitions, but being able to use definitions would be much easier to do.
