### ISSUE TITLE
"on entity death" event automatically erases flags on non-player entities?

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1575]
I'm trying to do something where when an entity with a specific flag dies, something binding it to the player is erased. All's fine and dandy, but when I use the `on entity death` event, it tells me that the entity does not have the flag, even though I've confirmed twice that the flag exists, and was attached on the entity. It only tells me that the dead entity has a flag when it's a player, not when it's a mob.

I'm using Denizen Developmental build 144, with Spigot 1.8.8.

My script is this:
```yaml
staffitem_enjalu_functions:
  type: world
  debug: true
  
  events:
    on player damages entity:
    - if '<context.damager.item_in_hand.scriptname||null>' == 'staffitem_enjalu'
    {
      - if '!<context.damager.has_flag[enjalu_rage_victim]>' && '!<context.entity.has_flag[enjalu_rage_against]>'
      {
        - take 'iteminhand'
        - playsound '<player>' 'sound:ITEM_BREAK' 'volume:1' 'pitch:1'
        - flag '<context.damager>' 'enjalu_rage_victim:<context.entity>'
        - flag '<context.entity>' 'enjalu_rage_against:<context.damager>'
        - if '<context.entity.is_player>'
        {
          - sidebar 'set' 'title:<&d>enjalu<&sq>s Hook of Rage' 'values:+75% damage from <context.entity.name>' 'players:<context.damager>'
          - sidebar 'set' 'title:<&d>enjalu<&sq>s Hook of Rage' 'values:+75% damage against <context.damager.name>|-50% damage against everyone else' 'players:<context.entity>'
        }
        else
        {
          - if '<context.entity.custom_name||null>' != 'null'
          {
            - sidebar 'set' 'title:<&d>enjalu<&sq>s Hook of Rage' 'values:+75% damage from <context.entity.custom_name>' 'players:<context.damager>'
          }
          else
          {
            - sidebar 'set' 'title:<&d>enjalu<&sq>s Hook of Rage' 'values:+75% damage from <context.entity.name.replace[_].with[ ]>' 'players:<context.damager>'
          }
        }
        - queue 'clear'
      }
      - if '<context.entity.has_flag[enjalu_rage_against]>'
      {
        - determine 'passively' 'cancelled'
        - actionbar '<&c>This entity is already affected by enjalu<&sq>s Hook of Rage!' 'targets:<context.damager>'
        - queue 'clear'
      }
      - if '<context.damager.has_flag[enjalu_rage_victim]>'
      {
        - determine 'passively' 'cancelled'
        - actionbar '<&c>You already have enjalu<&sq>s Hook of Rage activated!' 'targets:<context.damager>'
        - queue 'clear'
      }
    }
    else if '<context.damager.item_in_hand.scriptname||null>' == 'staffitem_enjalu' && 
    {
      - determine 'passively' 'cancelled'
      - actionbar '<&c>You already have enjalu<&sq>s Hook of Rage activated!' 'targets:<context.damager>'
    }
    else if '<context.damager.item_in_hand.scriptname||null>' == 'staffitem_enjalu' && '<context.damager.has_flag[enjalu_rage_victim]>'
    {
      - determine 'passively' 'cancelled'
      - actionbar '<&c>You already have enjalu<&sq>s Hook of Rage activated!' 'targets:<context.damager>'
    }
    - queue 'clear'
    
    on entity death:
    - if '<context.entity.has_flag[enjalu_rage_against]>'
    {
      - sidebar 'remove' 'players:<context.entity.flag[enjalu_rage_against]>'
      - flag '<context.entity.flag[enjalu_rage_against]>' 'enjalu_rage_victim:!'
      - if '<context.entity.is_player>'
      {
        - sidebar 'remove' 'players:<context.entity>'
        - flag '<context.entity>' 'enjalu_rage_against:!'
      }
    }
    - if '<context.entity.has_flag[enjalu_rage_victim]>'
    {
      - sidebar 'remove' 'players:<context.entity.flag[enjalu_rage_victim]>'
      - flag '<context.entity.flag[enjalu_rage_victim]>' 'enjalu_rage_against:!'
      - if '<context.entity.is_player>'
      {
        - sidebar 'remove' 'players:<context.entity>'
        - flag '<context.entity>' 'enjalu_rage_victim:!'
      }
    }
    - queue 'clear'
    
    on entity damages entity:
    - if '<context.damager.has_flag[enjalu_rage_against]>'
    {
      - if '<context.entity.has_flag[enjalu_rage_victim]>'
      {
        - determine 'passively' '<context.final_damage.mul[1.50]>'
      }
      else
      {
        - determine 'passively' '<context.final_damage.mul[0.7]>'
      }
    }
    - queue 'clear'
```
