### ISSUE TITLE
Cancelling "on entity spawns" doesn't work

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1591]
I'm using Denizen Developmental build 173, Spigot 1.11.2.

When I try to cancel the `on entity spawns` event, mobs still spawn. I'm not sure if it's because I'm doing something wrong.

The script is below:
```yaml
builder_flat1 world_maintenance:
  type: world
  debug: false
  
  events:
    on entity spawns:
    - if '<li@CHUNK_GEN|DEFAULT|NATURAL|NETHER_PORTAL|JOCKEY.contains[<context.reason>]>' && '<context.location.world.name>' == 'builder_flat1'
    {
      - determine 'passively' 'cancelled'
    }
```
