### ISSUE TITLE
Question: NPC respawn location

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1602]
I want this NPC respawn at their respawn location instead of last location.

How can i do it please ?

This is the denizen save file:
```
NPCs:
  '487':
    Flags:
      RESPAWN_LOCATION:
      - l@103.50815559040616,50.0,163.64469795304947,82.05,-7.019043E-4,delerorn
```

This is the citizens save file (in citizens folder) :

```
  '487':
    metadata:
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE0OTA1MTQxNTkyNjksInByb2ZpbGVJZCI6ImQ0ODEwZjNhNDZlNTQxZmU4MzFiY2FmZGQzYTlmZjcyIiwicHJvZmlsZU5hbWUiOiJPcnVzczciLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kNjQyYWYxZTQ5NzAzNzI3NWIyNThmNTQ0ZmRkYmRjNjc0NmU4MDE3NTk3Y2E2OTg4ZTY2NTMxMDVjYzIifX19
      cached-skin-uuid-name: oruss7
      cached-skin-uuid: d4810f3a-46e5-41fe-831b-cafdd3a9ff72
      player-skin-name: oruss7
      player-skin-signature: vu/rPgf6QhaAqfWPHxcFgaUqBvCiOuQqgk6M2Nts/N66kzYS+yxJmeuP1G5xc/IrOOOHJAhq1gVdLOYj9dqpqTYvmcQ7mLYyR47Z/T5BMTP8m3jEDBC+jwY8LigZ0iX4yOpBQRWGs0/M6/PlIRM24r4ypUeI/+eP5V/2PJ3yL9NmfVFGrPU3fhGg93PRoaq90ahub1L3DjMBcjoTLSBH8Ni0uvw740ydybX0gxSwOOlp3jSuOLCibWDkaGV01EwnIKKPZ783RNAZZLDTH4elMHC3CO0qh4lLOiXNosiZLV3Q863ZtwwXZFtBIWmjGj28lf+GuwG+c5dKIyEZ7Kxf198xtW13CW618I2LHAqeJ/wMVZxLUkeL1lAtAtK8pC9XWYRI2anrxrjZPJzVaEyCVuDkln6o4czCykOjHWhEFQ9gd5PD7p8RyFcMUyq9Pht61Npp6kbPFV2401i5NgnqmVqmm9j5r9spfGVMshzUFgRxLLoWKR97RdXfptKA9M+18KCSZsAbB5jldqObFEDR7QJub+0CfmQBZDWK1Y1WZ9p8k8QBK5qihBxl2moDgiEzrFxuBwe9CNI27kV36rSi84+spHt9q0BspMapfPmYeEEhE3LBPSBcOmyPnOwL+vcrimTQYomzoXTf5kl7/lY86Y8vEmo8kCsgLIT0MARSC+o=
      player-skin-use-latest: false
      protected: false
      collidable: false
    name: §9Garde Paix
    uuid: 87ceca8d-c43d-49ed-a304-8f01c1868518
    traits:
      gravity:
        enabled: false
      location:
        world: delerorn
        x: '103.521'
        y: '50.0'
        z: '164.485'
        yaw: '1.2117080688476562'
        pitch: '-1.7731517553329468'
      equipment:
        hand:
          type: DIAMOND_SWORD
          amount: 1
          durability: 0
          mdata: 0
      spawned: true
      type: PLAYER
      health:
        animatedeath: false
        respawnondeath: true
        respawndelayinseconds: 60s
        respawnlocation: <npc.flag[respawn_location]>
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      inventory:
        '0':
          type: DIAMOND_SWORD
          amount: 1
          durability: 0
          mdata: 0
      assignment:
        assignment: SEWERSENTRYGUARDQUEST_1
      triggers:
        enabled:
          CHAT: true
          CLICK: true
          PROXIMITY: true
          DAMAGE: false
        duration:
          CLICK: 2.0
          PROXIMITY: 5.0
        radius:
          CLICK: 8
          PROXIMITY: 5
      sentinel:
        stats_ticksSpawned: 1862461
        stats_timesSpawned: 630
        stats_arrowsFired: 0
        stats_potionsThrow: 0
        stats_fireballsFired: 0
        stats_snowballsThrown: 0
        stats_eggsThrown: 0
        stats_skullsThrown: 0
        stats_pearlsUsed: 0
        stats_punches: 83
        stats_attackAttempts: 253
        stats_damageTaken: 46.755341863632246
        stats_damageGiven: 63.0
        range: 20.0
        damage: -1.0
        armor: 0.9
        health: 20.0
        ranged_chase: false
        close_chase: true
        invincible: false
        fightback: true
        attackRate: 30
        attackRateRanged: 30
        healRate: 30
        guardingUpper: 0
        guardingLower: 0
        needsAmmo: false
        safeShot: true
        respawnTime: 100
        chaseRange: 100.0
        enemyDrops: false
        enemyTargetTime: 0
        speed: 1.0
        warning_text: ''
        greeting_text: ''
        greet_range: 10.0
        autoswitch: false
        accuracy: 0.0
        ignores:
          '0': OWNER
      pushable:
        toggle: false
        returnable: false
        delay: 2
      owner:
        owner: server
        uuid: ''
    traitnames: equipment,sentinel,type,owner,location,pushable,health,spawned,assignment,constants,mounttrait,lookclose,inventory,triggers
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: false
```

Thanks
