### ISSUE TITLE
Does Denizen have something like a conditional operator?

### ISSUE THREAD

**Issue by shroudedcode** [DenizenScript/Denizen-For-Bukkit#1663]
I have an inventory where players can toggle settings by clicking on items. The settings are saved as tags and are displayed in the lore of the items.

```yml
settings_item_mentions:
  type: item
  material: i@book_and_quill
  display name: <&6>Mention notifications
  lore:
  - <&7>Whether you get notified
  - <&7>when a player mentions
  - <&7>your name in chat.
  - ""
  - <player.has_flag[mentions_disabled].not>
```

At the moment the last line of the lore says *`true`* or *`false`* depending on the current setting. I obviously want to make this a bit more user-friendly and replace it with *`Enabled`* and *`Disabled`*.

In JavaScript I would use [the conditional operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) to solve this:
```js
!player.hasFlag('mentions_disabled') ? '<&a>Enabled' : '<&c>Disabled'
```
Is there currently such a thing in Denizen? It doesn't have to be an operator, a tag would do the job as well.
