### ISSUE TITLE
waitable "- midi" causes queue to remain stuck

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1677]
Denizen Developmental build 263, Spigot 1.12.1

When you run the `~midi` command, the rest of the queue is stuck on pause forever. I tested for this by running the following:
```
/ex run sample_midi_script id:<player.uuid>_sample_midi
```
With this task script:
```yaml
sample_midi_script:
    type: task
    speed: 0
    script:
    - ~midi file:Denizen <player>
    - narrate "end of the midi"
```
