### ISSUE TITLE
angry mech for wolf

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1699]
Hello,

Angry mech seems not working with that code:

```
BadWolf:
    type: entity
    entity_type: e@wolf[angry=true]
    custom_name: <red>Bad Wolf
    age: adult
```
or
```
BadWolf:
    type: entity
    entity_type: e@wolf
    custom_name: <red>Bad Wolf
    angry: true
    age: adult
```

Thanks
