### ISSUE TITLE
<context.entity.scriptname> returns null

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1728]
Hello,

The tag <context.entity.scriptname> in the event "on player damages entity" returns "null"
However the entity is created by an entity script. :/

Here the entity script : 
```
skel_test_red:
  type: entity
  entity_type: e@skeleton[has_ai=true;skeleton=wither;custom_name_visible=true;invulnerable=false;max_health=10;health=10]
  custom_name: <&c>Test_Red
```
