### ISSUE TITLE
Unfilled tags that are finally filled

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Denizen-For-Bukkit#1731]
Hello,
I found a very strange about how itemscripts are handled, i think.

Here the log :

https://one.denizenscript.com/haste/46794

Here the scripts:

```yaml
babylone_commands:
  type: command
  debug: true
  name: b
  description: Systeme Babylone
  usage: /b
  aliases:
  - babylone
  script:
    - inject locally <c.args.get[1].escaped||help>
  invite:
    - if <yaml[<pl.uuid>].contains[babylone.guilde].not> queue clear
    - if <yaml[<pl.uuid>].read[babylone.rang].is[==].to[Maitre].not> && <yaml[<pl.uuid>].read[babylone.rang].is[==].to[Main].not> queue clear
    - if <server.has_flag[invit_<yaml[<pl.uuid>].read[babylone.guilde]>]> {
      - narrate format:babylone "Une invitation pour votre guilde a déjà été générée, veuillez patienter encore <server.flag[invit_<yaml[<pl.uuid>].read[babylone.guilde]>].expiration.formatted>"
      - queue clear
    }
    - if <pl.inventory.can_fit[guilde_invitation].not> {
      - narrate format:babylone "<&c>Libérez un espace de votre inventaire pour générer une invitation"
      - queue clear
    } else {
      - give guilde_invitation
      - flag server invit_<yaml[<pl.uuid>].read[babylone.guilde]> duration:15m
    }
```

```yaml
babylone_invit_event:
  type: world
  debug: true
  events:
    on player left clicks with paper:
    - if <context.item.scriptname||false> == guilde_invitation {
      - if <yaml[<pl.uuid>].contains[babylone.guilde]> {
        - narrate format:babylone "Vous êtes déjà membre d'une guilde"
        - take iteminhand
        - queue clear
      }
      - define guilde <context.item.nbt[guilde]>
      - yaml id:b_%guilde% set membres.uuid:->:<pl.uuid>
      - yaml id:b_%guilde% set membres.noms:->:<pl.name>
      - yaml id:b_%guilde% set journal.civ:->:<&d><util.date.time.day>/<util.date.time.month>/<util.date.time.year><&sp><&sp><&sp><util.date.time.twentyfour_hour><n><&2><&l><pl.name><&sp>rejoint<&sp><context.item.nbt[guilde].to_titlecase>.
      - yaml id:b_%guilde% 'savefile:/babylone/guildes/<def[guilde].to_titlecase>.yml'
      - yaml id:<pl.uuid> set babylone.guilde:%guilde%
      - yaml id:<pl.uuid> set babylone.rang:Membre
      - yaml id:<pl.uuid> 'savefile:/joueurs/<pl.uuid>.yml'
    }

```

```yaml
guilde_invitation:
  type: item
  debug: true
  material: i@paper[nbt=li@guilde/<yaml[<pl.uuid>].read[babylone.guilde]>]
  display name: "<&a>Invitation à rejoindre <&b><yaml[<pl.uuid>].read[babylone.guilde].to_titlecase>"
  lore:
  - "<&f>Cliquer droit avec cette invitation"
  - "<&f>pour rejoindre la Guilde <&b><yaml[<pl.uuid>].read[babylone.guilde].to_titlecase>"
```
