### ISSUE TITLE
Anvil inventory does not display correct information sometimes

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1740]
Anvil inventory doesn't seem to be able to display proper information when I try to make the XP cost in the `on player prepares anvil craft item` event higher than 39.

Example scripts you can use:
```yaml
anvil_example1:
    type: world
    events:
        on player prepares anvil craft item:
        - determine 40
```
```yaml
anvil_example1:
    type: world
    events:
        on player prepares anvil craft item:
        - determine passively i@stone
        - determine 40
```
When I first open up the anvil inventory and put an iron helmet in the first slot, the cost will be "Too expensive" (as expected) but the X through the arrow will disappear. When I take the helmet out and put it back in, the X reappears and the "Too expensive" message seems to stay. However, clicking the second slot and/or the result slot alternatively will cause the display to flicker.

There are many other ways to cause the inventory to display wrong information, like putting another iron helmet in the second slot and trying to rename it (it will cause the anvil recipe to become "craftable", but exiting the inventory will update the player's inventory with the correct items).

No errors appear in console.
