### ISSUE TITLE
Inventory parsing nonexistent NBT incorrectly for items sharing the same itemscript

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1743]
This bug shows up in two ways, using `<in@inventory.list_contents.parse[nbt[key]]>` and this script:
```
- foreach <in@inventory.list_contents> {
    - narrate "<def[value].nbt[key]>"
}
```
All items without an item script return the expected values for the NBT key.

------
You can replicate using the following steps:
1. Create an itemscript using any NBT, and give yourself one. Example:
```yaml
samplestone:
    type: item
    material: i@stone[nbt=key/0]
    display name: "Version 0"
```
2. Edit the itemscript such that the NBT key does not exist on the updated version. Give yourself one. It is important that you do not edit any other instances of the item in your inventory. Example:
```yaml
samplestone:
    type: item
    material: i@stone
    display name: "Version null"
```
Afternote: You do not need to give yourself another instance of the item. You just need the two previous copies, one with the NBT key `key` and one without.

3. Give the itemscript the NBT key again. It can be any value. Example:
```yaml
samplestone:
    type: item
    material: i@stone[nbt=key/99999]
    display name: "Version 99 999"
```
4. Run `/ex narrate <player.inventory.list_contents.parse[nbt[key]]>` or run this script:
```yaml
sample_inventory_parser:
    type: task
    script:
    - foreach <in@inventory.list_contents> {
        - narrate "<def[value].nbt[key]>"
    }
```
You will see that any instance of the item with the NBT key `key` will return the expected value (in this example, "`0`"), but any instance of the item without the NBT key `key` will return the value in the file, not "`null`".
