### ISSUE TITLE
Notable removing issue

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1847]
The output of `/version` on my server is: CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

The output of `/version denizen` on my server is: version: 1.0.3-SNAPSHOT (build 471-DEV), core version: 1.20 (Build 168)

(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/50775
The issue is:

My problem is that I have 11 notable to delete. But only 6 of them get deleted (Only the one starting with "Guilde"). The number linked to the text "territoire" is random

```
Cuboids:
  guilde_territoire4_guilde_1: -48,0,208,Centre|-33,255,223,Centre
  ruine_territoire2_guilde_1: -64,0,224,Centre|-49,255,239,Centre
  ruine_territoire6_guilde_1: -48,0,240,Centre|-33,255,255,Centre
  ruine_territoire8_guilde_1: -32,0,224,Centre|-17,255,239,Centre
  guilde_territoire5_guilde_1: -48,0,224,Centre|-33,255,239,Centre
  ruine_territoire5_guilde_1: -48,0,224,Centre|-33,255,239,Centre
  ruine_territoire10_guilde_1: -48,0,192,Centre|-33,255,207,Centre
  ruine_territoire9_guilde_1: -32,0,240,Centre|-17,255,255,Centre
  ruine_territoire7_guilde_1: -32,0,208,Centre|-17,255,223,Centre
  ruine_territoire4_guilde_1: -48,0,208,Centre|-33,255,223,Centre
  guilde_territoire11_guilde_1: -48,0,176,Centre|-33,255,191,Centre
  ruine_territoire1_guilde_1: -64,0,208,Centre|-49,255,223,Centre
  guilde_territoire2_guilde_1: -64,0,224,Centre|-49,255,239,Centre
  ruine_territoire11_guilde_1: -48,0,176,Centre|-33,255,191,Centre
  guilde_territoire3_guilde_1: -64,0,240,Centre|-49,255,255,Centre
  ruine_territoire3_guilde_1: -64,0,240,Centre|-49,255,255,Centre
```
