### ISSUE TITLE
Using item scripts in click events always causes warnings

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1869]
Server version: build 494-DEV
Denizen version: version git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2)

The issue is: 

Whenever I use an item script item in a click event I get the warning even tho the material name is correct in terms of 1.13.2

LobbyCompass:
  type: item
  debug: false
  material: i@compass
  display name: '<gold><bold>Serverwahl'
  lore:

ERROR! Material ID and data magic number support is deprecated and WILL be removed in a future release.

**Comment by mcmonkey4eva** [comment]
Tested this:
```yml
test:
    type: world
    events:
        on player right clicks with LobbyCompass:
        - narrate "wow you clicked me"

LobbyCompass:
  type: item
  debug: false
  material: i@compass
  display name: '<gold><bold>Serverwahl'
```
Then ran `/ex give LobbyCompass` and right clicked the air with it.
Narrate showed, no errors occurred.

Please provide sufficient information to replicate the issue.
