### ISSUE TITLE
PlayerClicksBlock error - right clicking air in creative mode

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#1939]
We had a user post this error in discord: https://one.denizenscript.com/paste/53184

I was able to replicate the bug using this short test script:
```yml
test_script:
  type: world
  events:
    on player right clicks with glass_bottle:
    - take <context.item>
```
The bug is pretty specific - it only occurs when you right click air while in creative mode and set your held item to air.

I found this relevant open spigot issue: https://hub.spigotmc.org/jira/browse/SPIGOT-3020

Not sure if this is in-scope for Denizen to fix. Told the user to do a `- wait 1t` if the player is in creative mode.
