### ISSUE TITLE
Spigot serialized objects to dObjects

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#1976]
Spigot has a way to serialize things like ItemStacks - we should add tags to convert that data into dObjects. Tag might look like `<server.parse_bukkit_item[<item_text_here>]>` and probably also a tag for entities. For example, a serialized itemstack from spigot is:

```
    ==: org.bukkit.inventory.ItemStack
    v: 1963
    type: BLUE_STAINED_GLASS
    amount: 64
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §1§lShattered Glass
      enchants:
        KNOCKBACK: 2
        DAMAGE_ALL: 5
        SILK_TOUCH: 1
        DURABILITY: 3
```
