### ISSUE TITLE
Block translation names broken

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2190]
Went to start outputting material names and noticed that a lot of materials don't print translated_name correctly:
```
> version
[01:49:46 INFO]: This server is running Paper version git-Paper-183 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[01:49:46 INFO]: Checking version, please wait...
[01:49:46 INFO]: Previous version: git-Paper-176 (MC: 1.15.2)
[01:49:46 INFO]: You are 1 version(s) behind
> version Denizen
[01:49:49 INFO]: Denizen version 1.1.4-SNAPSHOT (build 4697-DEV)
[01:49:49 INFO]: Author: The DenizenScript Team
```

![image](https://user-images.githubusercontent.com/29823405/79420186-6aa89600-7f86-11ea-86e3-94390881e2b0.png)

It seems to break for all placeable blocks. After doing a bit of testing I found that this will display the correctly translated name:
`/ex narrate <&translate[block.minecraft.stone]>`

No idea if `block` vs `item` are the only differentiators involved, will probably require some digging or some nms work to get the string.

**Comment by mergu** [comment]
The builtin denizen `is_block` tag works to differentiate these for all blocks other than wall banners. Here's a hacky script I threw up to cycle through all the items to see if that check could be used:
```
test_mats:
  type: command
  name: blah
  script:
    - define start <context.args.get[1]||1>
    - foreach <server.list_materials.get[<[start]>].to[<[start].add[9]>].parse[as_material]>:
      - if <[value].is_block>:
        - narrate <[value].translated_name.replace[item].with[block]>
      - else:
        - narrate <[value].translated_name>
    - narrate "<element[(Next)].on_click[/blah <[start].add[10]>]>"
```
*_wall_banner doesn't work under `item` or `block`, so I've no idea what those should be. But they're not holdable anyways so I don't care much about them.
