### ISSUE TITLE
entity script, custom_name_visible=false does not hide the name tag.

### ISSUE THREAD

**Issue by hwgtok** [DenizenScript/Denizen-For-Bukkit#2258]
The output of `/version` on my server is: **This server is running Paper version git-Paper-240 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)**
The output of `/version denizen` on my server is: **Denizen version 1.1.7-SNAPSHOT (build 5117-DEV)**

The issue is:
in an entity script, custom_name_visible=false does not hide the name tag.

for example:
```
testent:
  type: entity
  entity_type: SKELETON
  custom_name: custom name set
  custom_name_visible: false
```
doing a ```/ex spawn testent``` will show the name tag

this also seems to apply to the alternate format of:
```
testent:
  type: entity
  entity_type: e@skeleton[has_ai=true;custom_name_visible=false;invulnerable=false;max_health=10;health=10]
```

There are no other plugins running on the server, this is a basic paper/denizens install only for testing, including running vanilla client.
