### ISSUE TITLE
Handle events using path of the class package

### ISSUE THREAD

**Issue by kassadGLA** [DenizenScript/Denizen-For-Bukkit#2285]
Hello.
I suggest adding the opportunity to use the API for events directly using the full path of the class package in the Denizen scripts.
Approximate code for an example:
```yaml
script:
    type: APIevent
    events:
        on ct.ajneb97.api.TurretPlaceEvent:
            - define locationX <getLocation().getX()>
            - define locationY <getLocation().getY()>
            - define locationZ <getLocation().getZ()>
```

In this example, the API of the ComplexTurrets plugin is used and the coordinates of a turret that a player is deploying is obtained.

The idea is borrowed from another plugin which is ConditionalEvents which is a simple version of the scripting engine and has this functionality. At the moment, I must use this plugin as an intermediary between Denizen and the target plugin whose API is to be used. [LINK](https://ajneb97.gitbook.io/conditionalevents/custom-events)

Best regards.
