### ISSUE TITLE
Chat trigger matching order changes when regex is used

### ISSUE THREAD

**Issue by aeheathc** [DenizenScript/Denizen-For-Bukkit#260]
Background info:

I have a script for an NPC to act as an interface to the plugin AbilityTrader.
Right-clicking gives a list of chat triggers available. To buy a Merchant ability, the player would type "buy merchant" at the NPC. The idea is, if the player types "buy" by itself or with an unrecognized ability name, the NPC would instead remind them that they need to use a valid ability name with the word 'buy'. However, if the player says something with no keywords in it at all, the NPC will tell the player to right click for a guide.
Here is my script:

``` yaml
'abilitytrader':
  Type: Interact
  Requirements:
    Mode: None
  Steps:
    1:
      Click Trigger:
        Script:
        - CHAT "Welcome. I can give you <blue>info<green> on your current licenses, <blue>list<green> all
          available licenses, or take orders to <blue>buy<green> or <blue>rent<green> licenses."
      Chat Trigger:
        1:
          Trigger: "Give me my current license /info/."
          Script:
          - NARRATE "<npc.name> quickly flips through some papers and slides one onto the counter,
            slamming his finger down next to your name."
          - EXECUTE AS_OP "ability info"
        2:
          Trigger: "/List/ the licenses."
          Script:
          - NARRATE "<npc.name> points to his clipboard."
          - EXECUTE AS_OP "ability list"
        3:
          Trigger: "/buy/"
          Script:
          - IF <player.chat_history> contains 'merchant'
              EXECUTE AS_OP "ability add <player.name> buy merchant true"
            ELSE
              CHAT "If you want to buy a license, it has to be one with a Buy price set."
        4:
          Trigger: "/rent/"
          Script:
          - IF <player.chat_history> contains 'suicide'
              EXECUTE AS_OP "ability add <player.name> rent /suicide true"
            ELSE
              CHAT "If you want to rent a license, it has to be one with a Rent price set."
        5:
          Trigger: "/regex:.+/"
          Script:
          - CHAT "Uh... you might want to try right-clicking."
```

The bug here is this: The script as given works exactly as expected, however, if I change the buy/rent chat triggers to use regex so that the player's entire text is shown in the "To NPC" message (as in `Trigger: "/regex:buy.*/"`) then **the bottom catch-all trigger will take precedence over the other regex based triggers but not over the non regex triggers** and the player is unable to buy anything. I know it's not just a case of the buy regex not matching because removing the catch-all will cause the regex-ified buy trigger to start working again.

So it seems that the order of precedence for chat trigger matching will be strange when more than one of the triggers is regex based alongside some non regex based triggers.
