### ISSUE TITLE
listener problem

### ISSUE THREAD

**Issue by sk0rms** [DenizenScript/Denizen-For-Bukkit#296]
this is an abstract from my daily-mission script. The script in generell seems to be working, but if i complete a listener the script is running twice! i have searched for hours now, but i couldnt find an answer. 

```
'Daily':
    type: world
    events: 
        on player join:
        - runtask 'script:DailyCheck'
        on daily command:
        - if '<flag.p:DailyMissionMinenQTY || None>' == 'None'
          narrate '<&2>You already completed the daily mission.'
        - if '<flag.p:DailyMissionMinenQTY || None>' == 'None'
          queue clear
        - narrate '------------------------------------------------------------'
        - narrate '<&l><&n><&7>DAILY-MISSION-INFO<&co>'
        - narrate 'Day - <flag.p:daily>'
        - narrate 'Quest 1<&co> <&6>Kill 10 <flag.p:DailyMissionJagenFormatted>. <&7>Done<&co> <flag.p:DailyMissionJagenCounter.asint>/10.'
        - narrate 'Quest 2<&co> <&6>Mine <flag.p:DailyMissionMinenQTY.asint> <flag.p:DailyMissionMineFormatted>. <&7>Done<&co> <flag.p:DailyMissionMinenCounter.asint>/<flag.p:DailyMissionMinenQTY.asint>.'
        - narrate '<&o>Complete one of the quest above for you daily mission.'
        - narrate '------------------------------------------------------------'
        - determine fulfilled
'DailyCheck':
    type: task
    script:
    - if '<flag.p:dailycooldown>' == 'true'
      narrate '<&2>You already completed the daily mission.'
      else runtask 'script:DailyMission'
'DailyMission':
    type: task
    script:
    - random 2
    - flag player 'DailyMissionJagen:SPIDER'
    - flag player 'DailyMissionJagen:ZOMBIE'
    - random 2
    - flag player 'DailyMissionMine:coal_ore'
    - flag player 'DailyMissionMine:21'
    - LISTEN KILL TYPE:ENTITY NAME:<flag.p:DailyMissionJagen> QTY:1 'SCRIPT:DailyMissionBeimJagen'
    - LISTEN BLOCK TYPE:BREAK BLOCK:<flag.p:DailyMissionMine> QTY:1 'SCRIPT:DailyMissionBeimMinen'
    - if '<flag.p:DailyMissionJagen>' == 'SPIDER'
      flag player 'DailyMissionJagenFormatted:Spiders'
      else flag player 'DailyMissionJagenFormatted:Zombies'
    - if '<flag.p:DailyMissionMine>' == 'coal_ore'
      flag player 'DailyMissionMineFormatted:Coal'
      else flag player 'DailyMissionMineFormatted:LapisLazuli'
    - flag player 'DailyMissionJagenCounter:0'
    - flag player 'DailyMissionMinenCounter:0'
    - if '<flag.p:DailyMissionMine>' == 'coal_ore' flag player     'DailyMissionMinenQTY:10'
      else flag player 'DailyMissionMinenQTY:5'
    - narrate '<&4>Daily Mission started. Type <&f>/daily <&4>for more info!'
'DailyMissionBeimJagen':
    type: task
    script:
    - if <player.location.world> == 'world' flag player 'DailyMissionJagenCounter:+'
    - narrate '<&7>Daily Mission<&co> <flag.p:DailyMissionJagenCounter.asint>/10 <flag.p:DailyMissionJagenFormatted>'
    - if '<flag.p:DailyMissionJagenCounter>' > 9 runtask 'script:DailyStageCheck'
      else LISTEN KILL TYPE:ENTITY NAME:<flag.p:DailyMissionJagen> QTY:1 'SCRIPT:DailyMissionBeimJagen'
'DailyMissionBeimMinen':
    type: task
    script:
    - if <player.location.world> == 'world' flag player 'DailyMissionMinenCounter:+'
    - narrate '<&7>Daily Mission<&co> <flag.p:DailyMissionMinenCounter.asint>/<flag.p:DailyMissionMinenQTY.asint> <flag.p:DailyMissionMineFormatted>'
    - if '<flag.p:DailyMissionMinenCounter>' > 9 && '<flag.p:DailyMissionMineFormatted>' == 'Kohle' runtask 'script:DailyStageCheck'
      else if '<flag.p:DailyMissionMinenCounter>' > '4' && '<flag.p:DailyMissionMineFormatted>' == 'LapisLazuli' runtask 'script:DailyStageCheck'
      else LISTEN BLOCK TYPE:BREAK BLOCK:<flag.p:DailyMissionMine> QTY:1 'SCRIPT:DailyMissionBeimMinen'
'DailyStageCheck':
    type: task
    script:
    - narrate '<&4>Daily Mission completed!'
    - if '<flag.p:daily||none>' == 'none'
      runtask 'script:dailytag1'
      else if '<flag.p:daily>' == Day2' runtask 'script:dailytag2'
      else if '<flag.p:daily>' == 'Day3' runtask 'script:dailytag3'
      else if '<flag.p:daily>' == 'Day4' runtask 'script:dailytag4'
      else if '<flag.p:daily>' == 'Day5' runtask 'script:dailytag5'
      else runtask 'script:dailytaghigh'
    - runtask 'script:DailyFlagClear'
```

Edit: changed text from german to english :D

Description: Checks on player join, if daily mission is aviable. - If aviable sets a hunting and a mining mission (Spider or Zombie and Coal or Lapis). If one of them is completed you're done with the daily. i did not copy the rewardscripts and the script for clearing the flags, because they are not nessecary for my question.
