### ISSUE TITLE
Task finishes in wrong spot.

### ISSUE THREAD

**Issue by tenowg** [DenizenScript/Denizen-For-Bukkit#32]
This is a hard one to explain, so I will do it in order, first here is the scripts:

``` yml
Tavvarr Stolen Goods:
  Type: Trigger
  Requirements:
    Mode: None
  Steps:
    '1':
      Click Trigger:
        Script:
        - NARRATE So they sent you? Don't look like much.
        - NARRATE What I need from you is to discover who ran
        - NARRATE off with half my inventory last night.
        - NARRATE Yes, thats right, half.
        - WAIT 1
        - NARRATE My guess is, the thief is stashing his loot
        - NARRATE nearby.
        - NARRATE Theres no way in hell he could move that much
        - NARRATE rukkshire vary far from here.
        - WAIT 1
        - NARRATE Please, you have to find my ale.
        - NARRATE Will you do this for me?
      Chat Trigger:
        '1':
          Trigger: /accept/
          Script:
          - NARRATE Great!! Return the items if you find them.
          - NARRATE (Maybe to the north there is a camp)
          - PLAYERTASK LOCATION banditcamp 1 15 Tavvarr go to Bandit Camp
          - FINISH
        '2':
          Trigger: /decline/
          Script:
          - NARRATE Figures, farewell.
Tavvarr Stolen Goods Two:
  Type: Trigger
  Requirements:
    Mode: All
    List:
    - ITEM MELON_BLOCK 10
    - FINISHED Tavvarr Stolen Goods
    - FINISHED Tavvarr go to Bandit Camp
  Steps:
    '1':
      Click Trigger:
        Script:
        - NARRATE Thanks so much for finding my Melons.
        - NARRATE Here take this for helping me.
        - NARRATE Also I will let Rukksharr know how you
        - NARRATE helped me.
        - TAKE MELON_BLOCK 10
        - EXECUTE ASNPC money give <PLAYER> 100
        - EXECUTE ASNPC xp <PLAYER> 10
        - NARRATE (Receive 10 xp, 100 Stacks, advance group)
        - FINISH
Tavvarr Stolen Goods Two Failed:
  Type: Trigger
  Requirements:
    Mode: All
    List:
    - -ITEM MELON_BLOCK 10
    - FINISHED Tavvarr Stolen Goods
  Steps:
    '1':
      Click Trigger:
        Script:
        - NARRATE Please return with the Melons.
Tavvarr Stolen Goods Two Cheat:
  Type: Trigger
  Requirements:
    Mode: All
    List:
    - ITEM MELON_BLOCK 10
    - FINISHED Tavvarr Stolen Goods
    - -FINISHED Tavvarr go to Bandit Camp
  Steps:
    '1':
      Click Trigger:
        Script:
        - NARRATE This is not MY inventory, please
        - NARRATE don't try to give me someone elses goods.
        - NARRATE Go get MY inventory.
Tavvarr go to Bandit Camp:
  Type: Task
  Script:
  - NARRATE You enter the Bandit Camp looking for the
  - NARRATE Melon Blocks for Tavvarr.
  - FINISH
```

Ok, it starts out ok, you get the first quest, it assigns the task after you accept it... The part that is the problem, if you try to cheat and turn in the melons before you have done the Task, it will work fine the first time, but then if you click him again it will "complete" the task then run the cheat part of the script again, and then if you click him again, it will run the completed script and take the melons.

Let me try to outline it better:

1) Click to talk to Tavvarr
2) chat "accept" (it gives the task to goto bandit camp, but you already have 10 melons so you try to complete)
3) Click and try to complete quest, he says melons are not his, go get his melons
4) Click again in frustration, It completes "Tavvarr go to Bandit Camp" and again says go get his melons.
5) Click again, complete the quest "Tavvarr Stolen Goods Two"

So you never had to really goto the bandit camp to complete the quest.
