### ISSUE TITLE
Add a FIRST # AND ANY # requirement mode

### ISSUE THREAD

**Issue by spaceemotion** [DenizenScript/Denizen-For-Bukkit#322]
In my current code I somehow need a requirement that checks for a number of requirements that definitely have to be met, but it also has some optional requirements.

I would suggest adding a `FIRST # AND ANY #` mode to allow this function.

Example:

``` yaml
Mode: FIRST 2 AND ANY 1
List:
- TIME NIGHT
- WEATHER SUNNY
- (other requirement)
- (and another one)
- (hey, another one!)
```
