### ISSUE TITLE
Listen Block errors with the 0.9.2

### ISSUE THREAD

**Issue by Peridoks** [DenizenScript/Denizen-For-Bukkit#357]
I have been having a problem with block listeners. Before I updated to the newest dev build, my listen script didn't give me any errors, but none of them actually counted when you did the action it was supposed to be listening for. Now that I've updated I can get LISTEN KILL to work just fine but the same LISTEN BLOCK command that didn't give me any errors before is giving me an error. Did the syntax for LISTEN BLOCK change or something? I've been searching and trying all sorts of things but it still gives me an error no matter what I try.

Here is my listen script:

```
  Chat Trigger:
    1:
      Trigger: /Yes/, I suppose.
      Script:
      - ENGAGE
      - CHAT "Great!"
      - WAIT 1
      - CHAT "Here are your seeds."
      - GIVE Seeds QTY:10
      - WAIT 1
      - CHAT "By the way, if you don't have a hoe, you should talk to the farmer inside."
      - WAIT 1
      - CHAT "Once you have a hoe you just need to use it on some dirt and plant the seeds."
      - WAIT 1
      - CHAT "Simple, right?"
      - LISTEN BLOCK ID:Seeds1 'SCRIPT:PlantSeeds1' TYPE:BUILD BLOCK:Stone QTY:1
      - ZAP
      - DISENGAGE
```

I realize it says stone instead of seeds in the listen command. I was just trying the most basic item since it was giving me an error.
