### ISSUE TITLE
Possible insight into the known issue of <player.chat_history> lagging one chat behind...

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#525]
Okay, so the <player.chat_history> tag has been an issue for quite a while; frequently it lags one chat behind.  Recently I stumbled upon an interesting pattern/workaround...perhaps it might be a clue as to where to start looking for a fix...

It seems that (after a player chats) the first use of the <player.chat_history> tag will always be one chat behind...it doesn't matter how you call the tag (narrate using it, store it in a flag, determine it, whatever). This seems to make the tag "catch up," so that subsequent uses of the tag will return the correct string.  In the following code, there are 5 calls to the tag, after chatting (4 in the same script, 1 in a different script...I could've made 'em all narration statements, but a little variety makes the point better)  Commenting out one or more from the top will cause the next call to be wrong, but all subsequent calls will be correct. Weird, huh?  In my case, when I need to use the <player.chat_history> for something, storing it in a dummy flag does the trick.

(btw, thanks Monkey for the Github code block format info...)

Cheer,
Doppler

```
ChatHistoryBug:
    type: interact
    steps:
        Greeting*:
            chat trigger:
                1:
                    trigger: "You typed /regex:alpha|beta|gamma|delta/."
                    script:
# Call 1:
                    - determine <player.chat_history> passively
# Call 2:                    
                    - narrate "<yellow> <player.chat_history>"
# Call 3:
                    - flag player "DummyVariable:<player.chat_history>"
                    - narrate "<green>Stored flag<&co> <player.flag[DummyVariable]>"
# Call 4:
                    - narrate "<dark_purple> <player.chat_history>"
                    - run CheckForChatHistory instantly
                    - zap step:Greeting

CheckForChatHistory:
    type: task
    script:
    - flag player DummyVariable:!
# Call 5:
    - narrate "<gold> <player.chat_history>"
```
