### ISSUE TITLE
how i can check items in the inventory

### ISSUE THREAD

**Issue by Wolf2323** [DenizenScript/Denizen-For-Bukkit#587]
i don't know where i can check if a player has a specific item in the inventory
i try out something like this

```
'QuestStart':
    type: world
    events:
       on ?????:
       - .......
```

the item is a gold nugget and it is in a chest and if the player take the item a script has to run
