### ISSUE TITLE
Characters tags <&lt> and <&gt> don't seem to display via procedure script.

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#599]
As the description says...

```
TestCommand:
    type: world
    events:
        on test command:
        - determine passively fulfilled
        - narrate "The less-than sign is <proc:less_than> and the greater-than sign is <proc:greater_than> but they don't display now."

less_than:
# I threw a few extra tags in there just to make sure they were being transferred...
    type: procedure
    script:
    - determine "<&2><&lt><&5>"

greater_than:
    type: procedure
    script:
    - determine "<&3><&gt><&6>"
```

Other codes seem to work fine.
