### ISSUE TITLE
run locally doesn't inherit the calling script's queue speed...

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#649]
...as demonstrated below. I'm not entirely sure where it's speed comes from, but it isn't the config.yml default speed either.  Maybe accidentally hardcoded or a typo?

```
TempTest:
    type: task
    speed: 30t
    script:
    - narrate "(slow) START"
    - narrate "(slow) Get ready..."
    - narrate "(slow) Get set..."
    - narrate "(slow) Go!"
    - ~run locally p:TempTest2
    - narrate "DONE"
    TempTest2:
    - narrate "(fast) ONE"
    - narrate "(fast) TWO"
    - narrate "(fast) THREE"
    - narrate "(fast) FOUR"
```
