### ISSUE TITLE
Misleading queue error (or perhaps a bug) when using random with braces

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#684]
Not sure if this is by design or an oversight...the first script works, the second results in a somewhat misleading "ERROR! Cannot use determine in this queue!"

```
Test1:
    type: procedure
    script:
    - random 3
    - determine "one"
    - determine "two"
    - determine "three"        
Test2:
    type: procedure
    script:
    - random {
        - determine "one"
        - determine "two"
        - determine "three"
      }
```

...the error makes it sound like the queue containing the random (the procedure) can't use a determine command. Also...shouldn't the second one work? Or is there a reason why it can't with the braces?
# moreworkforyoumorphan
