### ISSUE TITLE
How to execute commands or tasks using inventory scripts

### ISSUE THREAD

**Issue by vittoriom94** [DenizenScript/Denizen-For-Bukkit#707]
Hi, do you know how to execute commands or a task using the inventory script? 
For example, if the player clicks on the slot 1, it will run the task Slot1Task (or a command) and the player can't transfer items between his inventory and the virtual one.

In alternative, can I limit the number of items a player can take from an inventory? For example, I have an inventory with a Sword and a Pickaxe, the player can pick only one and then the inventory will be closed.

This is my code:

``` YAML
BlacksmithInventoryTutorial:
  type: inventory
  inventory: CHEST
  title: Blacksmith
  size: 9
  slots:
  - "[] [] [] [] [ItemStickTutorial] [] [] [] []"
```

then I open it with the command:

```
- inventory open d:in@BlacksmithInventoryTutorial
```
