### ISSUE TITLE
nested logic problem

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#715]
Took me a while to whittle this one down to the basic problem...this script narrates nothing (the final narrate never gets executed, according to the debug log):

``` YAML
logic_prob:
    type: task
    script:
    - if false {
        - narrate "This doesn't show."
      }
      else {
        - if true define words "This should show" else define words "This should not show"
        - narrate "%words%"
      }
```

Whereas this script narrates "null":

``` YAML
logic_prob:
    type: task
    script:
    - if false {
        - narrate "This doesn't show."
      }
      else {
        - if true define words "This should show"
        - narrate "%words%"
      }
```
