### ISSUE TITLE
YAML increase action not increasing value

### ISSUE THREAD

**Issue by BlackCoyote** [DenizenScript/Denizen-For-Bukkit#716]
command i'm trying to do: 

Ex yaml id:checklistdata set globallists.spawn[3]:+:1
or
Ex yaml id:checklistdata set globallists.spawn[3]:++

how it looks in the yaml file:

``` YAML
globallists:
  spawn:
  - TheBlackCoyote
  - open
  - '1'
```

(2 spaces in front of spawn)

debug:
http://mcmonkey.org/paste/2435

as seen in the debug the way i do it doesn't increase the value in the yaml.
actually setting the value  (  :3 instead of :++ )  does work.
I'm not sure whether this is a bug or if i'm doing something wrong
Help would be appreciated! :D
