### ISSUE TITLE
Script cool-down seems to have a one-second minimum

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#720]
Perhaps this is hard-coded to prevent lag...one second is probably fine for interact scripts, but for 'on player clicks' events it is just long enough to be irritating. Regardless of the duration units, it seems to be 1 second before the script can fire (as shown by `<s@Test.cooldown[<player>]>`). The debug log shows the correct duration set. For example (I set it to 5t to illustrate the discrepancy):

``` YAML
Test:
    type: world
    events:
        on player right clicks block:
        - narrate "<s@Test.cooldown[<player>]>"
#        - narrate "<s@Test.requirements.check>"
        - if !<s@Test.cooled_down[<player.name>]> queue clear
        - narrate "Cooled down!"
        - cooldown 5t s:Test
```

Oh, also, the documented tag `<s@Test.requirements.check>` seems not to work (always returns null, at least with world scripts)...maybe an old tag, or maybe it is used only to check on the status of interact scripts...either way, the docs could be clearer for that tag...

``|/D

...I'll work on that sig, emoticon...it seems a bit off.
