### ISSUE TITLE
QUESTION related to name changes

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#779]
Hey there,

when i use flag command like
`- flag player Noob:+:1`

Then it gets saved in the save.yml like

```
Players:
  Goma_Terzu:
    Flags:
      Noob:
      - '1'
```

So what happens when i change my name to Morphan2 ingame? Are those flags lost? I tried to save it like

`- flag player Testflag:1 player:p@<player.uuid>`

But it appears in the save under the real name Goma again.
