### ISSUE TITLE
Nested Triggers

### ISSUE THREAD

**Issue by Razick** [DenizenScript/Denizen-For-Bukkit#800]
I am trying to write a script for a banker with nested options. For example, when the user first clicks the banker, he says "Hello, would you like to open a new account?"

The user can either select yes or no. If however, the user selects yes, the banker then asks for confirmation because a fee may be charged. So the user can either select yes or no.

I tried nesting the chat triggers in several different ways, and then tried moving the nested sections to separate steps and zapping to them. Nothing seems to work right though. 

If this is explained somewhere I apologize, but I can't seem to find it. Here's what I have right now so you can get a better idea of what I am trying to do, and hopefully help me sort it out:

```
open_account: 
  type: interact 
  steps: 
    1: 
        click trigger: 
            script: 
            - chat 'Hello, would you like to open a new account? *yes *no *close' 
        chat trigger:
            1:
                trigger: /yes/
                script:
                - chat "If this isn't your first account, there may be a small fee."
                - wait 1
                - chat "Is that okay? *yes *no"
                - zap step:2
    2:
        chat trigger:
            1:
                trigger: /yes/
                script:
                - wait 1
                - chat "Okay, just one moment please."
                - wait 5
                - chat 'Almost done...'
                - wait 1
                - execute as_player 'bank open <player>'
                - wait 1
                - chat 'Okay. You should be all set!'
                - wait 1
                - chat 'Just talk to the other bankers if you need to manage your account.'
                - zap step:1
                trigger: /no/
                script:
                - wait 1
                - chat 'Okay, come see me if you change your mind.'
                - zap step:1
```
