### ISSUE TITLE
Error Parsing Script

### ISSUE THREAD

**Issue by Razick** [DenizenScript/Denizen-For-Bukkit#801]
I'm running into a little bit of a strange error on one of my scripts:

17.07 14:28:06 [Server] INFO been skipped. No internal error - is the file empty? 
17.07 14:28:06 [Server] INFO ERROR! Woah! Error parsing /loan.yml! This script has 

The file isn't empty, and I validated the yaml as well. I looked through the file and can't seem to find anything wrong, but it might be a rule I don't know.

EDIT:

Also, is there a way to allow a player to input a value and have the npc read it? For example, could the npc ask: 

How much would you like to borrow?

and then use whatever value the player provides in a command?: execute as_player 'bank loan <user_input>'

```
loan: 
  type: assignment 
  interact scripts: 
  - 100 loan

loan: 
  type: interact 
  steps: 
    1: 
        click trigger: 
            script: 
            - chat 'Hello, would you like to take out a *loan or make a *payment? *info' 
        chat trigger:
            1:
                trigger: I want to get a /loan/
                script:
                - chat "You can borrow up to 1,000 thalers."
                - wait 1
                - chat "But be careful! You'll have to repay with interest within 30 days."
                - chat "Is that okay? *yes *no"
                - zap step:2
            2:
                trigger: /info/rmation about loans
                script:
                - wait 1
                - chat "If you have the required permissions, you can borrow up to 1,000 thalers."
                - wait 1
                - chat "You'll have 30 days to repay what you owe plus our weekly interest rate."
                - wait 1
                - chat "The interest rate changes from time to time."
                - wait 1
                - chat "You should ask a bank manager if you have any questions" 
            3:
                trigger: I want to make a /pay/ment
                script:
                - wait 1
                - chat "Okay, how much do you want to pay? *1 *10 *25 *100 *250 *1000"
                - zap step:4            
    2:
        chat trigger:
            1:
                trigger: /yes/
                script:
                - wait 1
                - chat "Okay, just one moment please."
                - wait 2
                - chat 'How much would you like to borrow? *1 *10 *50 *100 *250 *500 *1000'
                - zap step:3
            2:
                trigger: /no/
                script:
                - wait 1
                - chat 'Okay, come see me if you change your mind.'
                - zap step:1
    3:
        chat trigger:
            1:
                trigger: /1000/
                script:
                - wait 1
                - chat "Alright, please sign here..."
                - wait 2
                - chat "Thank you. Almost done..."
                - wait 2
                - execute as_player 'bank loan 1000'
                - wait 1
                - chat "All done. Please come back when you are ready to make a payment."
                - zap step:1
            2:
                trigger: /500/
                script:
                - wait 1
                - chat "Alright, please sign here..."
                - wait 2
                - chat "Thank you. Almost done..."
                - wait 2
                - execute as_player 'bank loan 500'
                - wait 1
                - chat "All done. Please come back when you are ready to make a payment."
                - zap step:1
            3:
                trigger: /250/
                script:
                - wait 1
                - chat "Alright, please sign here..."
                - wait 2
                - chat "Thank you. Almost done..."
                - wait 2
                - execute as_player 'bank loan 250'
                - wait 1
                - chat "All done. Please come back when you are ready to make a payment."
                - zap step:1
            4:
                trigger: /100/
                script:
                - wait 1
                - chat "Alright, please sign here..."
                - wait 2
                - chat "Thank you. Almost done..."
                - wait 2
                - execute as_player 'bank loan 100'
                - wait 1
                - chat "All done. Please come back when you are ready to make a payment."
                - zap step:1
            5:
                trigger: /50/
                script:
                - wait 1
                - chat "Alright, please sign here..."
                - wait 2
                - chat "Thank you. Almost done..."
                - wait 2
                - execute as_player 'bank loan 50'
                - wait 1
                - chat "All done. Please come back when you are ready to make a payment."
                - zap step:1
            6:
                trigger: /10/
                script:
                - wait 1
                - chat "Alright, please sign here..."
                - wait 2
                - chat "Thank you. Almost done..."
                - wait 2
                - execute as_player 'bank loan 10'
                - wait 1
                - chat "All done. Please come back when you are ready to make a payment."
                - zap step:1
    4:
        chat trigger:
            1:
                trigger: /1000/
                script:
                - wait 1
                - chat "Okay, just a second..."
                - wait 2
                - execute as_player 'bank payback 1000'
                - wait 1
                - chat "All done. Let me know if you need anything else."
                - zap step:1
            2:
                trigger: /250/
                script:
                - wait 1
                - chat "Okay, just a second..."
                - wait 2
                - execute as_player 'bank payback 250'
                - wait 1
                - chat "All done. Let me know if you need anything else."
                - zap step:1
            3:
                trigger: /100/
                script:
                - wait 1
                - chat "Okay, just a second..."
                - wait 2
                - execute as_player 'bank payback 100'
                - wait 1
                - chat "All done. Let me know if you need anything else."
                - zap step:1
            4:
                trigger: /25/
                script:
                - wait 1
                - chat "Okay, just a second..."
                - wait 2
                - execute as_player 'bank payback 25'
                - wait 1
                - chat "All done. Let me know if you need anything else."
                - zap step:1
            5:
                trigger: /10/
                script:
                - wait 1
                - chat "Okay, just a second..."
                - wait 2
                - execute as_player 'bank payback 10'
                - wait 1
                - chat "All done. Let me know if you need anything else."
                - zap step:1
            6:
                trigger: /1/
                script:
                - wait 1
                - chat "Okay, just a second..."
                - wait 2
                - execute as_player 'bank payback 1'
                - wait 1
                - chat "All done. Let me know if you need anything else."
                - zap step:1
```
