### ISSUE TITLE
Zap is saving under playername instead of uuid

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Denizen-For-Bukkit#810]
When a script contains a `zap step:something` command, the data is being saved under the old-style player name key instead of the fancy new uuid key:

```
dScript: {}
a_saves:
  version: '2'
Players:
  B7:
    B74924ECFDEB44A9986B12DC385E5719:
      Flags:
        LOGIN_NAME:
        - Dopplizzle
  Dopplizzle:
    Scripts:
      TESTDIALOGUE:
        Current Step: step_2
Listeners:
  B7: {}
```
