### ISSUE TITLE
entity damages entity event failing to pass definitions to procedure script

### ISSUE THREAD

**Issue by goodbyebluemonday89** [DenizenScript/Denizen-For-Bukkit#870]
Can't seem to get definitions to be passed to a procedure script when within this event. Works fine when in command event. I'm not sure what others may be affected. 

```
TestScript:
  type: world
  events:
    on entity damaged by entity:
    - define entity <context.entity>
    - announce %entity%
    - announce "<proc[EntityDefinition]> is an entity"

EntityDefinition:
  type: procedure
  script:
  - determine "%entity%"
```

and I can make a new ticket for this, if required, but the `<context.damage>` tag in this isn't properly calculated when using sentry. Despite the sentry's strength level and the actual amount of health lost, it always determines the tag as 1.0.
