### ISSUE TITLE
Saving FINISH script flag as player nick, not UUID

### ISSUE THREAD

**Issue by nevy96** [DenizenScript/Denizen-For-Bukkit#880]
Hi! When I use `- FINISH` command for my script it saves the value as a nick of player, not UUID. Is it a bug or desired action?

Tested on Denizen 0.9.6-SNAPSHOT (build 1540)

My saves.yml:

``` yml
dScript: {}
a_saves:
  version: '2'
Listeners:
  '29': {}
Global:
  Flags:
    SANDS:
    - '41.0'
Players:
  '29':
    29606063A6D54F9B8109A0AF85B299D4:
      Scripts:
        GOLDBARSTART:
          Current Step: '3'
        PRZEWOZNIKROZMOWA:
          Current Step: '1'
      Flags:
        ODLAMKI:
        - '10'
  Kosciany:
    PRZEWOZNIKSCRIPT:
      Completed: 2
```
