### ISSUE TITLE
Suggestion: Requirements for shopkeeper

### ISSUE THREAD

**Issue by tenowg** [DenizenScript/Denizen-For-Bukkit#9]
Requirement for a script, HASINVENTORYSPACE, would detect is there was space in the players inventory.

HASINVENTORYSPACE #

or a Requirement for the amount of space available in a chest at a bookmark

CHESTINVSPACE [location] #

Also

CHESTHASITEM [location] [item](#)

Was thinking this would make it so denizens could be StopKeepers with the right script

something like

```
Requirements:
  Mode: All
  List:
  - MONEY 36
  - CHESTHASITEM DIRT 1
  - HASINVENTORYSPACE 1
```

Another request might be a way to set variables in an options statement. So you could do something like this.
Would also request the IF statement and the END or could use what is already there FAIL which would end the script, as well as a CHECKREQ... a runtime check of a requirement.

```
Chat Trigger:
  Trigger: /buy $/      //would be something that keys to a variable
  Script:
    - IF (CHECKREQ -MONEY %1):      // a % and a number would key to the variable value listed below
      - CHAT Seems you don't have enough money
      - END
    - CHAT here you go
    - TAKE MONEY %1
    - EXECUTE ASSERVER give <PLAYER> $1 // would be key of variable
  Options:
    - apple: 36
```

If you don't pull your hair out on this one... lol :)
