### ISSUE TITLE
Location Trigger Not Firing?

### ISSUE THREAD

**Issue by davidlohle** [DenizenScript/Denizen-For-Bukkit#90]
Hey Denizen team, absolutely love this plugin, but have a problem. I have a mutli-step quest, and it seems like my location trigger isn't firing, or something.

Here's the quest:

``` yaml
'hunter':
  Type: Trigger
  Requirements:
    Mode: ALL
    List:
    - -FINISHED hunter
  Steps:
    '1':
      Click Trigger:
        Script:
        - LOOK AT
        - CHAT "Hey I have a job for you if you are up for it."
        - CHAT "Can you go get me some string I'll pay you for them."
        - HINT short
      Chat Trigger:
        '1':
          Trigger: /Yes/ I'll get you some string.
          Script:
          - CHAT "Good bring me 25 string."
          - CHAT "Wait before you go you might need these."
          - GIVE 272 QTY:1
          - GIVE 299 QTY:1
          - FINISH
        '2':
          Trigger: /No/ Get your own string.
          Script:
          - CHAT "Then fuck off runt."
          - FAIL
'hunter checkfail1':
  Type: Trigger
  Requirements:
    Mode: ALL
    List:
    - FINISHED hunter
    - -FINISHED hunter checkall
    - -ITEM 287 25
  Steps:
    '1':
      Click Trigger:
        Script:
        - CHAT "When you have the 25 string come back talk to me, quit wasting my time peasant."
'huntercheckall':
  Type: Trigger
  Requirements:
    Mode: ALL
    List:
    - FINISHED hunter
    - -FINISHED huntercheckall
    - ITEM 287 25
  Steps:
    '1':
      Click Trigger:
        Script:
        - ENGAGE
        - TAKE 287 25
        - CHAT "Ahh yes, thank you my friend. Take this as payment for your time."
        - GIVE MONEY QTY:25
        - FINISH
        - DISENGAGE
'hunter2':
  Type: Trigger
  Requirements:
    Mode: ALL
    List:
    - FINISHED huntercheckall
    - -FINISHED hunter2
  Steps:
    '1':
      Click Trigger:
        Script:
        - CHAT "You have provin your self well my friend."
        - CHAT "I have a another job for you if your interested."
        - HINT short
      Chat Trigger:
        '1':
          Trigger: /Yes/ what is it this time?
          Script:
          - CHAT "Goto the east and deal with the issue that has arise in the skull caves."
          - FINISH
        '2':
          Trigger: /No/ you do it.
          Script:
          - CHAT "Then fuck off, I thought you were better then that."
          - FAIL

'skullcavefound':
  Type: Trigger
  Requirements:
    Mode: All
    List:
    - -FINISHED skullcavefound
    - FINISHED hunter2
  Steps:
    '1':
      Location:
        '1':
          Trigger: SkullCaves
          Script:
          - NARRATE "You have found the caves. Now kill the spiders and find the spiderhandlers secret."
          - SPAWN QTY:2 spider spiderspawn1
          - SPAWN QTY:2 spider spiderspawn2
          - SPAWN QTY:2 spider spiderspawn3
          - SPAWN QTY:2 cavespider spiderhandlerspawn
          - SPAWN QTY:3 spider spiderhandlerspawn
          - FINISH

'skullsecretfound':
  Type: Trigger
  Requirements:
    Mode: All
    List:
    - -FINISHED skullsecretfound
    - FINISHED skullcavefound
  Steps:
    '1':
      Location Trigger:
        '1':
          Trigger: skullsecretfound
          Script:
          - NARRATE "You have found the the Spider Handler's books.  Bring them back to Captain Jack."
          - FINISH
'hunter2check':
  Type: Trigger
  Requirements:
    Mode: All
    List:
    - FINISHED skullsecretfound
  Steps:
    '1':
      Click Trigger:
        Script:
        - ENGAGE
        - NARRATE "You hand Jack the books and tell him about the spiders."
        - CHAT "Hmm Interesting I will have the mage look at these..."
        - CHAT "I thank you very much Take these as a thank you of these kingdom."
        - GIVE 283 qty:2
        - GIVE HEROESEXP QTY:150
        - FINISH
        - DISENGAGE
```

I've set the bookmarks,

``` yaml
  Golui:
    Bookmarks:
      Location:
      - spiderspawn1 survival;-148.12405163323035;65.0;281.8669152745402;-144.70166;32.250015
      - spiderspawn2 survival;-136.60820505033732;64.0;271.6505770124574;-180.10303;14.850021
      - spiderspawn3 survival;-137.54463873796914;67.0;258.6868389879833;-178.60254;11.700017
      - spiderhandlerspawn survival;-136.82223093506184;67.0;243.51434386626994;-210.25049;24.749987
      - skullsecretfound survival;-137.68542365757403;67.0;246.51804374007952;-178.59863;27.449959
      - SkullCaves survival;-137.50841330746874;67.0;262.79366591938106;-178.75;14.249984
    '13': {}
```

And certainly have the requirements met:

``` yaml
  Protocol_7:
    hunter:
      Completed: 1
    huntercheckall:
      Completed: 1
    hunter2:
      Completed: 1
```

Here is the console output when I click on the NPC just to test.

```
23:30:34 [INFO] | OKAY! Highest scoring script is skullcavefound.
23:30:34 [INFO] +---------------------+
23:30:34 [INFO] +- Parsing click trigger: Golui/Protocol_7 -+
23:30:34 [INFO] | Getting current step:
23:30:34 [INFO] | ...current step not found, assuming '1'.
23:30:34 [INFO] | ERROR! Could not find script at:
23:30:34 [INFO] | skullcavefound.Steps.1.Click Trigger.Script
23:30:34 [INFO] | Check YML spacing, or is something spelled wrong in your script?
```

And Denizen is seeing that I walk over the bookmark

```
23:34:35 [INFO] [Denizen] [Location Trigger] 'Protocol_7' just walked over bookmark 'SkullCaves'
```

Is my quest script wrong or is there something else going on?
