### ISSUE TITLE
Broken Item Script Recipes

### ISSUE THREAD

**Issue by OzOwnz** [DenizenScript/Denizen-For-Bukkit#923]
When an item is crafted, such as:
```
pet_rock:
  type: item
  no_id: true
  material: "i@stone"
  display name: '<&r>Pet Rock'
  lore:
  - '<&7>A pet rock. Be'
  - "<&7>careful it doesn't"
  - '<&7>sneak away!'
  recipe:
  - i@stone|i@stone|i@stone
  - i@stone|i@stone|i@stone
  - i@stone|i@stone|i@stone
```
you are able to take an infinite number of items out of the outcome slot in the crafting table, and it doesn't take any items from the crafting grid.

I'm also having problems with one of my other food related scripts, but that's a different story.
