### ISSUE TITLE
Yes! No! Wait...

### ISSUE THREAD

**Issue by Morphan1** [DenizenScript/Denizen-For-Bukkit#978]
It seems that something somewhere is messing with something that it shouldn't be messing with.
Script nodes seem to translate "yes" as the boolean value "true" and "no" as the boolean value "false".
For example,
```
YesItem:
  type: item
  display name: yes
  material: green_wool
NoItem:
  type: item
  display name: no
  material: red_wool
```
Using `/ex give i@YesItem` will give you green wool named "true".
Using `/ex give i@NoItem` will give you red wool named "false".

Even keys get translated
```
InventoryOfIndecision:
  type: inventory
  inventory: chest
  size: 18
  definitions:
    yes: i@YesItem
    no: i@NoItem
  slots:
  - "[yes] [no] [yes] [no] [yes] [no] [yes] [no] [yes]"
  - "[true] [false] [true] [false] [true] [false] [true] [false] [true]"
```
Using `/ex inventory open d:in@InventoryOfIndecision` will open an inventory with only the second row filled, even though the actual definition names are "yes" and "no".

This includes script names as well.
```
Yes:
  type: task
  script:
  - narrate <script.name>
```
Using `/ex run s@Yes` does nothing.
Using `/ex run s@true` narrates "TRUE".

These are worked around fairly simply by wrapping quotes around the keys or values...
```
  display name: "yes"

  definitions:
    "yes": i@YesItem

"Yes":
```
...but it's pretty inconvenient to be writing scripts and suddenly run into this problem.
